language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run build
  - npm test

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    target-branch: gh-pages
    local-dir: demo-dist
  on:
    branch: master